allowBuilds:
  '@parcel/watcher': true
  core-js: true
  es5-ext: true
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - vue-router@5.4.0

overrides:
  '@vue/compiler-sfc': 3.5.43
  element-plus: 2.14.7
  pinia: 4.0.3
  vue: 3.5.43
  vue-router: 5.4.0
  '@tiptap/vue-3@3.31.0>@tiptap/extension-floating-menu': 3.31.0
  'unplugin-element-plus>unplugin': 3.4.0
patchedDependencies:
  element-plus@2.14.7: patches/element-plus@2.14.7.patch
